---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint -s .
  ansible-lint
  flake8

platforms:
  - name: centos
    command: /usr/sbin/init
    dockerfile: ../default/Dockerfile-centos8.j2
    groups:
      - cassandra
      - centos
      - python3
    image: centos:latest
    privileged: True

  - name: debian
    dockerfile: ../default/Dockerfile.j2
    groups:
      - cassandra
      - debian
    image: debian:latest

  - name: fedora
    command: /usr/sbin/init
    dockerfile: ../default/Dockerfile.j2
    groups:
      - cassandra
      - fedora
      - python3
    image: fedora:latest
    privileged: True

  - name: ubuntu
    dockerfile: ../default/Dockerfile.j2
    image: ubuntu:latest
    groups:
      - cassandra
      - ubuntu
    privileged: True

provisioner:
  name: ansible

  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"

  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: python3

  log: True

  options:
    limit: ${HOSTS}
    v: 1

  playbooks:
    converge: ../default/converge.yml
    prepare: ../default/prepare.yml

scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify

verifier:

  name: testinfra

  directory: ../default/tests

  options:
    connection: docker
    durations: 3
    v: 1
