###########################################
- name: Configure Solr as slave
  hosts: solr-2,solr-3,solr-4
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: lean_delivery.solr_cluster
      solr_instance_type: slave

- name: Configure Solr as master
  hosts: solr-1
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: lean_delivery.solr_cluster

#################################
- hosts: es-1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es-1"
      discovery.seed_hosts: "es-1:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: es-2,es-3,es-4
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es-1"
      discovery.seed_hosts: "es-1:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

##################################
- hosts: mongo-1
  become: yes
  roles:
    - role: stone-payments.mongodb

# - name: install mongodb replica set
#   host: all
#   roles: stone-payments.mongodb
#   vars:
#     mongodb_conf_bindIp: "0.0.0.0"
#     mongodb_replSet_enabled: true
#     mongodb_replSet_name: "someReplicaSetName" '{{ ansible_fqdn }}'
#     mongodb_replSet_master: "1.2.3.4" #must be an IP address
#     mongodb_replSet_key: "someLongKey" #optional, cross-replica authentication key
#     mongodb_replSet_member: "{{ ansible_eth1['ipv4']['address'] }}" #optional, specify a different IF for replication
#     mongodb_replSet_arbiter: "{{ true if inventory_hostname == 'hostThatIsArbiter' else false }}"
