###########################################
- name: Slaves Solr Config
  hosts: solr-2,solr-3,solr-4
  roles:
#    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: lean_delivery.solr_cluster
      solr_instance_type: slave
  vars:
    solr_version: '8.6.0'


- name: Master Solr Config
  hosts: solr-1
  roles:
  #  - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: lean_delivery.solr_cluster
  vars:
    solr_version: '8.6.0'
  
############################################
- hosts: es-1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_api_host: "0.0.0.0"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es-1"
      discovery.seed_hosts: "192.168.1.40:9300"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: es-2,es-3,es-4
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_data_dirs:
      - "/opt/elasticsearch"
    es_api_host: "0.0.0.0"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "es-1"
      discovery.seed_hosts: "192.168.1.40:9300"
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment

##################################
- hosts: mongo-1
  become: yes
  roles:
    - role: stone-payments.mongodb

# - name: install mongodb replica set
#   host: all
#   roles: stone-payments.mongodb
#   vars:
#     mongodb_conf_bindIp: "0.0.0.0"
#     mongodb_replSet_enabled: true
#     mongodb_replSet_name: "someReplicaSetName" '{{ ansible_fqdn }}'
#     mongodb_replSet_master: "1.2.3.4" #must be an IP address
#     mongodb_replSet_key: "someLongKey" #optional, cross-replica authentication key
#     mongodb_replSet_member: "{{ ansible_eth1['ipv4']['address'] }}" #optional, specify a different IF for replication
#     mongodb_replSet_arbiter: "{{ true if inventory_hostname == 'hostThatIsArbiter' else false }}"



#####################################################


- name: Example Playbook for the locp.cassandra Role

  hosts: cassandra-1
  become: yes
#  remote_user: root

  vars:
    cassandra_configuration:
      authenticator: PasswordAuthenticator
      cluster_name: MyCassandraCluster
      commitlog_directory: /data/cassandra/commitlog
      commitlog_sync: periodic
      commitlog_sync_period_in_ms: 10000
      data_file_directories:
        - /data/cassandra/data
      endpoint_snitch: GossipingPropertyFileSnitch
      hints_directory: "/data/cassandra/hints"
      listen_address: "{{ ansible_default_ipv4.address }}"
      partitioner: org.apache.cassandra.dht.Murmur3Partitioner
      saved_caches_directory: /data/cassandra/saved_caches
      seed_provider:
        - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
          parameters:
            - seeds: "{{ ansible_default_ipv4.address }}"
      start_native_transport: true
    cassandra_configure_apache_repo: true
    # Create an alternative directories structure for the Cassandra data.
    # In this example, the will be a directory called /data owned by root
    # with rwxr-xr-x permissions.  It will have a series of sub-directories
    # all of which will be defaulted to being owned by the cassandra user
    # with rwx------ permissions.
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/commitlog
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
    cassandra_regex_replacements:
      - path: cassandra-env.sh
        line: 'MAX_HEAP_SIZE="512M"'
        regexp: '^#MAX_HEAP_SIZE="1G"'
      - path: cassandra-env.sh
        line: 'HEAP_NEWSIZE="100M"'
        regexp: '^#HEAP_NEWSIZE="800M"'
      - path: cassandra-rackdc.properties
        line: 'dc=DC1'
        regexp: '^dc='
      - path: cassandra-rackdc.properties
        line: 'rack=RACK1'
        regexp: '^rack='
    cassandra_repo_apache_release: 311x

  roles:
    - role: locp.cassandra
