---
galaxy_info:
  author: Bernardo Donadio
  description: Role for disabling Huge Pages on Linux kernel persistently
  company: Stone Payments
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: EL
      versions:
      - 7
    - name: Ubuntu
      versions:
      - xenial    
  galaxy_tags:
  - system
  - tweaks
dependencies: []
